### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Grandnainconnu** [pnxtech/hydra#216]
Hello, I was wondering if this project is still active and maintained? 
Because when compilation there is quite a bit of warning including critical ones.

I also saw a `v2` branch in typescript, is it ready to use too?

Thank you in advance.

**Comment by cjus** [comment]
@Hetarnam yes - the project is very much alive and in production use at various companies. I moved the project after leaving Flywheel Sports and losing the resources that would continue to support the project. The TypeScript branch is dead - but not for lack of interest in moving to typescript - but rather a loss of resources devoted to the effort.   I'm currently working on a video tutorial course that explores the use of containerized microservices using Hydra.  Regarding the compilation concerns, I'll make a cleanup pass since those issues.

**Comment by Hetarnam** [comment]
Ok! Thank you for your answer, everything is opened for PR then?

**Comment by cjus** [comment]
Yes, but unless it's a bug fix it might be a good idea to first ask what you're interested in working on. ;-)

**Comment by Hetarnam** [comment]
What needs to be improved now then? 
And maybe the typescript branch would be a good idea?

**Comment by cjus** [comment]
Would you like to join the hydra slack channel to discuss?

**Comment by Technikkeller** [comment]
I would too ^^
Should I send you a email?

**Comment by cjus** [comment]
@Technikkeller yes the project is very much still active. I just sent you an invite.
In fact, we have a HydraPy for Python under development as well. https://pypi.org/project/hydra-py/

**Comment by jimjones26** [comment]
I would love to get an invite to the hydra slack channel.
